-- MySQL Script generated by MySQL Workbench
-- Sun Apr 11 00:03:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Scrapping Facebook Data Base
-- Guerra Cervantes Sergio Enrique

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Table Post
-- -----------------------------------------------------
DROP TABLE IF EXISTS Post ;

CREATE TABLE IF NOT EXISTS Post (
  idPost VARCHAR(50) NOT NULL,
  URL TEXT NOT NULL,
  Persona TEXT NOT NULL,
  Texto TEXT NOT NULL,
  PRIMARY KEY (idPost))
;

ALTER TABLE Post ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table Comentarios
-- -----------------------------------------------------
DROP TABLE IF EXISTS Comentarios ;

CREATE TABLE IF NOT EXISTS Comentarios (
  idComentarios VARCHAR(50) NOT NULL,
  Post_idPost VARCHAR(50) NOT NULL,
  Persona TEXT NOT NULL,
  Texto TEXT NULL,
  PRIMARY KEY (idComentarios, Post_idPost),
  FOREIGN KEY (Post_idPost)
  REFERENCES Post (idPost))
;

ALTER TABLE Comentarios ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table Respuesta
-- -----------------------------------------------------
DROP TABLE IF EXISTS Respuesta ;

CREATE TABLE IF NOT EXISTS Respuesta (
  idRespuesta INT NOT NULL AUTO_INCREMENT,
  Persona TEXT NULL,
  Texto TEXT NOT NULL,
  Comentarios_idComentarios INT NOT NULL,
  Post_idPost INT NOT NULL,
  PRIMARY KEY (idRespuesta, Comentarios_idComentarios, Post_idPost),
  FOREIGN KEY (Comentarios_idComentarios , Post_idPost)
  REFERENCES Comentarios (idComentarios , Post_idPost))
;

ALTER TABLE Respuesta ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table Compartir
-- -----------------------------------------------------
DROP TABLE IF EXISTS Compartir ;

CREATE TABLE IF NOT EXISTS Compartir (
  idCompartir INT NOT NULL AUTO_INCREMENT,
  Post_idPost INT NOT NULL,
  Persona VARCHAR(45) NULL,
  PRIMARY KEY (idCompartir, Post_idPost),
  FOREIGN KEY (Post_idPost)
  REFERENCES Post (idPost))
;

ALTER TABLE Compartir ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table Reacciones
-- -----------------------------------------------------
DROP TABLE IF EXISTS Reacciones ;

CREATE TABLE IF NOT EXISTS Reacciones (
  idReacciones INT NOT NULL AUTO_INCREMENT,
  Tipo VARCHAR(45) NULL,
  Persona VARCHAR(45) NULL,
  Post_idPost INT NOT NULL,
  PRIMARY KEY (idReacciones, Post_idPost),
  FOREIGN KEY (Post_idPost)
  REFERENCES Post (idPost))
;

ALTER TABLE Reacciones ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
