-- MySQL Script generated by MySQL Workbench
-- Tue May 11 21:13:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL,
  `URL` VARCHAR(45) NOT NULL,
  `Persona` VARCHAR(45) NOT NULL,
  `Texto` VARCHAR(200) NULL,
  PRIMARY KEY (`idPost`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT,
  `Post_idPost` INT NOT NULL,
  `Persona` VARCHAR(45) NOT NULL,
  `Texto` VARCHAR(45) NULL,
  PRIMARY KEY (`idComentarios`, `Post_idPost`),
  INDEX `fk_Comentarios_Post_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Post`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `Persona` VARCHAR(45) NULL,
  `Texto` VARCHAR(100) NOT NULL,
  `Comentarios_idComentarios` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idRespuesta`, `Comentarios_idComentarios`, `Post_idPost`),
  INDEX `fk_Respuesta_Comentarios1_idx` (`Comentarios_idComentarios` ASC) VISIBLE,
  INDEX `fk_Respuesta_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Comentarios1`
    FOREIGN KEY (`Comentarios_idComentarios`)
    REFERENCES `mydb`.`Comentarios` (`idComentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compartir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compartir` (
  `idCompartir` INT NOT NULL AUTO_INCREMENT,
  `Post_idPost` INT NOT NULL,
  `Persona` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompartir`, `Post_idPost`),
  CONSTRAINT `fk_Compartir_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reacciones` (
  `idReacciones` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  `Persona` VARCHAR(45) NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idReacciones`, `Post_idPost`),
  INDEX `fk_Reacciones_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Reacciones_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
